---
title: Greg Jordan-Detamore
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
    permalink: /portfolio/:name
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
email: greg@gregjd.com
description: 'I am a civic technologist interested in government, cities, transportation, and parks.'
baseurl: ''
url: http://www.gregjd.com
twitter_username: gjordandetamore
github_username: gregjd
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"

# Disqus post comments
disqus_shortname: gregjd

# Gems
gems:
  - jekyll-seo-tag

# Other
twitter:
  username: gjordandetamore
logo: /images/Profile_Pic_Square.png
social:
  name: Greg Jordan-Detamore
  links:
    - https://twitter.com/GJordanDetamore
    - https://github.com/gregjd
