# Site settings
title: Greg Jordan-Detamore
email: greg@gregjd.com
description: > # this means to ignore newlines until "baseurl:"
  Greg is a developer and designer interested in civic technology, 
  transportation, and planning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gregjd.com" # the base hostname & protocol for your site
twitter_username: gjordandetamore
github_username:  gregjd

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["smart"]

# Custom
permalink: /blog/:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
