---
title: Greg Jordan-Detamore
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
email: greg@gregjd.com
description: 'Greg is a developer, data/GIS analyst, and designer  interested in civic
  technology and geography.

'
baseurl: ''
url: http://www.gregjd.com
twitter_username: gjordandetamore
github_username: gregjd
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"

# Disqus post comments
disqus_shortname: username

# Gems
gems:
  - jekyll-seo-tag

# Other
twitter:
  username: gjordandetamore
logo: /images/Profile_Pic_Square.png
social:
  name: Greg Jordan-Detamore
  links:
    - https://twitter.com/GJordanDetamore
    - https://github.com/gregjd
